# Generated by Django 4.0.1 on 2022-01-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='history',
            field=models.TextField(default='some history', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(choices=[('1', 'Single'), ('2', 'Married')], default='1', max_length=2),
        ),
    ]
