# Generated by Django 4.0.1 on 2022-01-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formletter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.RemoveField(
            model_name='letter',
            name='diagnosis',
        ),
        migrations.AddField(
            model_name='patient',
            name='diagnoses',
            field=models.ManyToManyField(to='formletter.Diagnosis'),
        ),
    ]
