# Generated by Django 4.0.1 on 2022-01-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formletter', '0002_delete_client_remove_letter_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
