# Generated by Django 4.0.1 on 2022-01-09 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formletter', '0003_template_updated_at_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template', to='formletter.template'),
        ),
    ]
