# Generated by Django 4.0.1 on 2022-01-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formletter', '0003_alter_diagnosis_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_4',
            field=models.CharField(max_length=4),
        ),
    ]
